spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/ineternational_sim?useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: postgres
    platform: postgres
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:/db/migration
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 10
        generate-statistics: true
    show-sql: true
  application:
    name: visa-application-service
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
